#!/usr/bin/env bash

touch nixpkgparu
PKG="$1" #xclip -o without any argument will give all the value selected to BOOKMARK.

if grep -q "^$PKG$" ~/nixpkg; then
  dunstify "Naah!" "Package already exist."
else
  paru -S --needed $PKG && echo "$PKG" >> ~/nixpkgparu
  dunstify "Hey abhi" "Package name ""$PKG"" added to nixpkgs."
fi



