#!/usr/bin/env bash


options=$(seq 1 +1 153)

selected_option=$(echo -e "$options" | rofi -dmenu -p "Volume level:" -theme ~/rofi/files/launchers/type-1/vol_theme.rasi)

pulsemixer --set-volume $selected_option
